# Generated by Django 4.2.2 on 2023-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_doctor_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="app_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
