# Generated by Django 4.2.2 on 2023-07-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_appointment_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="department",
        ),
    ]
