# Generated by Django 4.2.2 on 2023-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_appointment_app_id_alter_appointment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
